
char ca_crt_rsa_1[] = {
    /* http://cacerts.digitalcertvalidation.com/TrustAsiaTLSRSACA.crt */
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIErjCCA5agAwIBAgIQBYAmfwbylVM0jhwYWl7uLjANBgkqhkiG9w0BAQsFADBh\r\n"
    "MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\r\n"
    "d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\r\n"
    "QTAeFw0xNzEyMDgxMjI4MjZaFw0yNzEyMDgxMjI4MjZaMHIxCzAJBgNVBAYTAkNO\r\n"
    "MSUwIwYDVQQKExxUcnVzdEFzaWEgVGVjaG5vbG9naWVzLCBJbmMuMR0wGwYDVQQL\r\n"
    "ExREb21haW4gVmFsaWRhdGVkIFNTTDEdMBsGA1UEAxMUVHJ1c3RBc2lhIFRMUyBS\r\n"
    "U0EgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgWa9X+ph+wAm8\r\n"
    "Yh1Fk1MjKbQ5QwBOOKVaZR/OfCh+F6f93u7vZHGcUU/lvVGgUQnbzJhR1UV2epJa\r\n"
    "e+m7cxnXIKdD0/VS9btAgwJszGFvwoqXeaCqFoP71wPmXjjUwLT70+qvX4hdyYfO\r\n"
    "JcjeTz5QKtg8zQwxaK9x4JT9CoOmoVdVhEBAiD3DwR5fFgOHDwwGxdJWVBvktnoA\r\n"
    "zjdTLXDdbSVC5jZ0u8oq9BiTDv7jAlsB5F8aZgvSZDOQeFrwaOTbKWSEInEhnchK\r\n"
    "ZTD1dz6aBlk1xGEI5PZWAnVAba/ofH33ktymaTDsE6xRDnW97pDkimCRak6CEbfe\r\n"
    "3dXw6OV5AgMBAAGjggFPMIIBSzAdBgNVHQ4EFgQUf9OZ86BHDjEAVlYijrfMnt3K\r\n"
    "AYowHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDgYDVR0PAQH/BAQD\r\n"
    "AgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAG\r\n"
    "AQH/AgEAMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3Au\r\n"
    "ZGlnaWNlcnQuY29tMEIGA1UdHwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2lj\r\n"
    "ZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwTAYDVR0gBEUwQzA3Bglg\r\n"
    "hkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29t\r\n"
    "L0NQUzAIBgZngQwBAgEwDQYJKoZIhvcNAQELBQADggEBAK3dVOj5dlv4MzK2i233\r\n"
    "lDYvyJ3slFY2X2HKTYGte8nbK6i5/fsDImMYihAkp6VaNY/en8WZ5qcrQPVLuJrJ\r\n"
    "DSXT04NnMeZOQDUoj/NHAmdfCBB/h1bZ5OGK6Sf1h5Yx/5wR4f3TUoPgGlnU7EuP\r\n"
    "ISLNdMRiDrXntcImDAiRvkh5GJuH4YCVE6XEntqaNIgGkRwxKSgnU3Id3iuFbW9F\r\n"
    "UQ9Qqtb1GX91AJ7i4153TikGgYCdwYkBURD8gSVe8OAco6IfZOYt/TEwii1Ivi1C\r\n"
    "qnuUlWpsF1LdQNIdfbW3TSe0BhQa7ifbVIfvPWHYOu3rkg1ZeMo6XRU9B4n5VyJY\r\n"
    "RmE=\r\n"
    "-----END CERTIFICATE-----\r\n"
};

char ca_crt_rsa_2[] = {
    /* http://cacerts.digitalcertvalidation.com/TrustAsiaTLSRSACA.crt */
        "-----BEGIN CERTIFICATE-----\r\n"
        "MIICljCCAX4CCQCbiHL3mQBt0TANBgkqhkiG9w0BAQsFADANMQswCQYDVQQDDAJj\r\n"
        "YTAeFw0xOTA0MjgxMzAxMzRaFw0yOTA0MjUxMzAxMzRaMA0xCzAJBgNVBAMMAmNh\r\n"
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6jY55kRcq37iyMGnEFn6\r\n"
        "NxQiLCXEx22POg+00LCJc7mzJugnd6BbbbRM2suEm+CMK6jgFYc5pkCua4KbTDkh\r\n"
        "H0DcQ8WFOsbcjQ9z3LG7L3PinZhkmse2EyHMCXx10rpcSiXkXpWd32yxW1Q4Sxy9\r\n"
        "EFnhTXzMJ80nRSnxr01KaBPogP+JwxBY+OVvdJCcwD835bi8HLVo+XgfhP2E09qe\r\n"
        "4pK/7XjklcKhPyLZIIAvm8hfinKPyFaNjGSr4MMtJniI5iC+iykpht4p9LnC3Q+c\r\n"
        "Reo0A4x1Pr+KbwvNHVdTudQm/hqTdkmRJGBQUSKkHCwyTDdTIDTp+t13gmW3RIic\r\n"
        "gwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQDDUgHyS3km8AHKW/cDdQhhNDBoY3RV\r\n"
        "+ttwtr1jEPxfO6L7OqpMJwiGOos7sODUqTNKwUJSw36ZUg9xFlMuEt6XQiq+Hyip\r\n"
        "8u5vVrDgJR/Rkeb2GDBKgUjajgSQG5FxQsKf+7HlcKVW14Nr7Ttr4LQETPiM6YG7\r\n"
        "VpE6gMq+Bi/F4fZr7yiDVIrOOiOz1LczTGAQzPS+VKY7q7bjUIy0dsFXX6EaR6zw\r\n"
        "G4tHKq3jsOUK9J5dT3KrS8RZEtWverRW0cWBr7ABecJtSsJ/9omqScT7/Pt65vkr\r\n"
        "qX7y4d8eYMVvKmGbp+hi9tMw2OrepvXiyOMw2ueD+XXO+NYGfrF6YUW5\r\n"
        "-----END CERTIFICATE-----\r\n"

};
